const DynamicImage = {
  faqicon: require("../assets/images/faqicon.png"),
  rightCheck: require("../assets/images/right_check.jpeg"),
  arrowDown: require("../assets/images/arrowDown/arrowDown.png"),
  splashImage: require("../assets/images/splash-image.png"),
  mainLogo: require("../assets/images/mainLogo.png"),
  termsIcon: require("../assets/images/terms_icon.png"),
  assIcon: require("../assets/images/icebreaker-icons.jpeg"),
  voiceIcon: require("../assets/images/voicemail-icons.jpeg"),
  likeIcon: require("../assets/images/like-icons.jpeg"),
  checkNormal: require("../assets/images/check_normal.png"),
  checkSelcted: require("../assets/images/check_selcted.png"),
  cameraIcon: require("../assets/images/camera.png"),
  cameraIcon1: require("../assets/images/camera1.png"),
  cleanIcon: require("../assets/images/clean.png"),
  VideoIcon: require("../assets/images/video-camera.png"),
  VideoIconShow: require("../assets/images/video-chat.png"),
  trackIcon: require("../assets/images/track.png"),
  attendanceIcon: require("../assets/images/upload.png"),
  uploadIcon: require("../assets/images/attendance.png"),
  VolumeIcon: require("../assets/images/voice.png"),
  deleteIcon: require("../assets/images/delete.png"),
  batchIcon: require("../assets/images/batch.png"),
  checkIcon: require("../assets/images/check.png"),
  logoutIcon: require("../assets/images/log_out_icon.png"),
  pickPdf: require("../assets/images/pickpdf.jpeg"),
  showpdf: require("../assets/images/showpdf.jpeg"),
  showtimer: require("../assets/images/timer.png"),
  chatIcon: require("../assets/images/chat_icon.png"),
};
export default DynamicImage;
